# Generated by Django 3.2 on 2024-08-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20240803_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
