# Generated by Django 3.2 on 2024-08-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20240803_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCommentBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
    ]
